services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"
    # Mount backend source for live code reload
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    # Use uvicorn with --reload for hot reload in dev
    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001} --reload
    # Uncomment for resilience in dev
    # restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # Mount frontend source for hot reload
    volumes:
      - ./frontend:/app
    # Install node_modules on container startup for dev
    entrypoint: ["sh", "-c", "yarn install && yarn run dev --host 0.0.0.0"]

